### ISSUE TITLE
[BUG] Cannot create a new project getting error 500

### ISSUE THREAD

**Issue by Ohicram** [jsonzilla/crashfix_webapp#19]
I've installed crashfix webapp on windows with xampp, it seems to be runnning and working, 
but when I try to create a new project I get the following error:
Error 500
Property "Project.require_exact_build_age" is not defined.

**Comment by jsonzilla** [comment]
Hi @Ohicram,

I hope this message finds you well. I'd like to kindly highlight the importance of adhering to the specified format for open issues. Would you mind providing all the parameters used during the project creation in the form? Specifically, details such as the version of the database and PHP would be immensely helpful. Without this information, it becomes challenging for me to provide the assistance you need.

Additionally, I've noticed that this error often occurs when PDB files are sent to the project. Your cooperation in providing these details would be greatly appreciated.

Thank you for your understanding and assistance.

**Comment by daveb49** [comment]
Hi jsonzilla - please see my question at 
    https://sourceforge.net/p/crashfix/tickets/9/
Sorry, I can't see where to correctly post this as a question... I apologize for putting it in this thread, but the thread was at least talking about PDB uploads. I tried to post as a question here, but the protocol suggests putting it on stackoverflow?
Happy to move the question there... let me know correct protocol

**Comment by Ohicram** [comment]
Thank you very much @jsonzilla for your quick reply. I apologize for the badly formatted question and for not providing any info.
I am using xampp 3.3.0
Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12
Database client version: libmysql - mysqlnd 8.2.12
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.2.12

Actually I had to fix a little bug in php file because of the new php version, specifically:
Fatal error: Array and string offset access syntax with curly braces is no longer supported in C:\xampp\htdocs\crashfix\protected\framework\utils\CFormatter.php on line 232

![image](https://github.com/jsonzilla/crashfix_webapp/assets/35306113/40d24c23-6d52-4330-abcd-327ff781b02b)
![image](https://github.com/jsonzilla/crashfix_webapp/assets/35306113/078b5620-7e9f-4300-ad6f-2fa2d741231e)
![image](https://github.com/jsonzilla/crashfix_webapp/assets/35306113/35ce1f59-1137-49fd-b101-66e1f3138ad9)

This is my user_params.ini
;-----------------------------------------------;
; CrashFix Web Application Parameters           ;
;-----------------------------------------------;

; Database Address.
db_connection_string='mysql:host=127.0.0.1;dbname=crashfix'

; User Name.
db_username=crashfix

; User Password.
db_password=admin

; Table Prefix.
db_table_prefix=tbl_

**Comment by Ohicram** [comment]
To solve this bug I had to add an additional field to the Project table called require_exact_build_age of type DATE
and to User table a INT field of type cur_project_id. 
Nonetheless when I tried to send the report it didn't correctly completed the operation.
Is this project supposed to be working and I am having bad configuration or has it been dismissed ?
![image](https://github.com/jsonzilla/crashfix_webapp/assets/35306113/f839ee26-d26d-40dd-a37c-6c9a5c81d3ed)

**Comment by Ohicram** [comment]
@daveb49 hey, I've the same issue as you too, I am not able either to upload pdb or send the crashreport

**Comment by daveb49** [comment]
Hi Ohicram... here's some notes on your issues...

1. On your php bugfix ...curly braces is no longer supported... in CFormatter.php:
   The same fix needs to be done in about 100 places, and was done in a commit in
   the GITHub fork of this project. Use the GITHub forks at
      https://github.com/jsonzilla/crashfix_webapp
      https://github.com/jsonzilla/crashfix_service
   
2. There are some other fixes in these forks and the Crashfix website is certainly
   running just fine and uploading crash zips for me using a Linux Ubuntu server
   running PHP 8.1.2-1ubuntu2.14 

3. In the website Administer|Projects menu, click to setup a New project then
   under Misc Options, set "Require exact build age for debugging symbols." to No
   and save the project

4. You may need to update CrashSender exe, I guess we should setup a GIT repo for
   that also. I did have to make some little changes to handle http redirects better.
   In your log that you screengrabbed (WTLDemo - Sending Error Report) notice there
   is a bad server response body:<DOCTYPE etc etc...
   You need to look at the txt logfile which has the full message, showing what
   actually happened. What's in the screengrab is a truncated long line just showing
   the start of this message.
   If someone can point me to a GIT repo forking CrashSender, I can add the commits
   I did locally here to fix this problem.

5. There is one other fix I haven't sent a pull request for yet. When loading the
   crashdump file, it scans the xml for all the modules (DLLs etc) and their file
   versions, timestamps etc. In my case this triggered another PHP problem in
   that the timestamp is stored as an unsigned int and was crashing the SQL INSERT
   statement until I added ... & 0x7fffffff; to trim off the sign bit.
   I made this little patch in protected/commands/PollCommand.php at line 811:
         $module->timestamp = $timeStamp & 0x7fffffff;   // daveb: protection as this is getting stored in a 32bit signed int field

   This stops it crashing and lets it load all the DLLs, but is not the correct
   solution. I think the database field should be made signed instead, but this
   requires changes in a few more places, plus some testing.
   So the timestamps loaded are not reliable in my implementation. Specifically,
   it was failing while loading the timestamp for ntdll.dll

6. I expect there are other little problems yet to be identified and resolved,
   but the implementation I have running now certainly uploads crash zips from the field
   and is a huge help in diagnosing bugs in our software from user crashes in the field.
   Until I can load PDBs, the only limitation really is that I have to download the
   crash zips received and analyze them locally, so I can load the PDBs and see the
   symbolic stack in full. The crashfix project is really really useful and certainly works.

**Comment by daveb49** [comment]
PS My CrashSender1403.exe variant was based on https://crashrpt.sourceforge.net/docs/html/compiling_crashrpt.html
Just looking for this now, I have only found an archived project here:  https://github.com/doo/CrashRpt
If someone can point me to an active GITHub repo for CrashSender, I'm happy to provide pull requests for
my changes, which we now use in our production distribution to end users so that crashes in the field can be uploaded
smoothly. We've been using this for a few years now and have fixed quite a few bugs based on these crashzip uploads.
This tool is one of the most useful tools we've ever seen, thanks to Oleg and collaborators for a fantastic project.

**Comment by jsonzilla** [comment]
https://github.com/jsonzilla/crashrpt/issues/10

> PS My CrashSender1403.exe variant was based on https://crashrpt.sourceforge.net/docs/html/compiling_crashrpt.html Just looking for this now, I have only found an archived project here: https://github.com/doo/CrashRpt If someone can point me to an active GITHub repo for CrashSender, I'm happy to provide pull requests for my changes, which we now use in our production distribution to end users so that crashes in the field can be uploaded smoothly. We've been using this for a few years now and have fixed quite a few bugs based on these crashzip uploads. This tool is one of the most useful tools we've ever seen, thanks to Oleg and collaborators for a fantastic project.

I think that is what you want @daveb49. (like @Mixaill wrote at https://github.com/jsonzilla/crashrpt/issues/10)
* https://github.com/CrashRpt/crashrpt2/commits/master
* https://gitlab.com/xvm/crashrpt2/-/commits/xvm (except crashsender: move report size position from subheader to link)

@Ohicram, I need some time to check. I'm sorry, but I don't have enough time until the weekend.

**Comment by Ohicram** [comment]
@jsonzilla don't worry Jason, thanks for it. At the end I think I will probably use another solution, I just wanted to report it. Maybe I will try to look into this in the future in my spare time just for fun/learning. It's really a nice project.
